development: &default
  adapter: postgresql
  encoding: unicode
  database: aelogica_development
  pool: 5
  host: localhost

test: &default
  adapter: postgresql
  encoding: unicode
  database: aelogica_test
  pool: 5
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: aelogica
  pool: 5
  username: postgres
  password: